theme: jekyll-theme-minimal
title: [To-Do Lift]
description: [To-Do Lift is an application made for athletes who want a simple view for their current workout,
as well as wanting to be able to save workouts, and track progress.]
logo: WorkoutList/Assets.xcassets/logo.imageset/Picture1.png
